---
title: "Online Store Sales Forecasting"
output: html_notebook
---

```{r load_libraries, include=FALSE}


if (!require(tidyverse))
  install.packages("tidyverse", repos = "http://cran.us.r-project.org")
if (!require(fpp3))
  install.packages("fpp3", repos = "http://cran.us.r-project.org")
if (!require(knitr))
  install.packages("knitr", repos = "http://cran.us.r-project.org")
if (!require(readxl))
  install.packages("readxl", repos = "http://cran.us.r-project.org")
if (!require(skimr))
  install.packages("skimr", repos = "http://cran.us.r-project.org")


library(tidyverse)
library(fpp3)
library(knitr)
library(readxl)
library(skimr)
library(distributional)

options(dplyr.summarise.inform = FALSE)

```

```{r pull_and_load_data, eval=FALSE, include=FALSE}

url<- "https://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx"
tmp <- tempfile(fileext = ".xlsx")
download.file(url, destfile = tmp, mode="wb")

online_store<- read_xlsx(tmp)

```

```{r save and load data}

#save(online_store,file = "online_store.rda")
load("online_store.rda")

```

# Exploratory Analysis


```{r examine data, echo=FALSE}

skim(online_store)

```

```{r}
online_store %>%
slice_min(na.omit(UnitPrice),n=10, with_ties = F) %>% kable()
```

```{r}
online_store %>%
slice_max(na.omit(UnitPrice),n=10, with_ties = F) %>% kable()
```

```{r}
online_store %>%
  mutate(length = str_length(StockCode)) %>%
  ggplot(aes(length))+
  geom_bar()
```


```{r}

online_store %>%
  mutate(length = str_length(StockCode)) %>%
  filter(length < 5) %>%
  distinct(StockCode, Description) %>% kable()
```


```{r}

online_store %>%
  mutate(length = str_length(StockCode)) %>%
  filter(length > 5) %>%
  distinct(StockCode, Description) %>% head(10) %>% kable()
```



```{r clean data, echo=FALSE}

online_store<- online_store %>%
  filter(Quantity > 0 , UnitPrice > 0, str_length(StockCode) %in% c(5,6))

```

```{r}
online_store %>%
slice_max(na.omit(Quantity), n=10) %>% kable()
```

```{r}
online_store<- online_store %>%
  filter(!InvoiceNo %in% c("581483", "541431"))
```


```{r examine data 2, echo=FALSE}

skim(online_store)

```



```{r}
online_store %>%
  mutate(fivedig = str_sub(StockCode, 1,5)) %>%
  filter(is.na(as.numeric(fivedig))) %>%
  distinct(StockCode, Description)
```

```{r}
online_store %>%
  group_by(Country) %>%
  summarise(revenue = sum(Quantity * UnitPrice)) %>%
  slice_max(na.omit(revenue), n=10) %>%
  ggplot(aes(reorder(Country, -revenue), revenue, fill = Country)) +
  geom_col()+
  theme(
    axis.text.x = element_text(
      size =  8,
      angle = 90,
      vjust = 0.5,
      hjust = 1
    ),
    legend.position = "none")+
  labs(x = "Country") +
  ggtitle("Revenue for Top 10 Countries")
```

```{r}
online_store <- 
  online_store %>%
  filter(Country == "United Kingdom") %>%
  mutate(
    Quanity = as.integer(Quantity),
    Revenue = Quantity * UnitPrice,
    InvoiceDate = as_date(InvoiceDate),
    product_code = str_sub(StockCode, 1,5)
    ) %>%
  group_by(product_code, InvoiceDate, InvoiceNo) %>%
  summarise(Quantity = sum(Quantity), Revenue = sum(Revenue)) %>%
  ungroup()
  
```
```{r}

online_store %>%
  group_by(InvoiceDate) %>%
  summarise(Quantity = sum(Quantity)) %>%
  ungroup() %>%
  ggplot(aes(InvoiceDate, Quantity)) +
  geom_point() +
  geom_smooth(method = "lm", se= FALSE) +
   labs(y = "Units Sold") +
  scale_x_date(date_labels = "%b %y", date_breaks  = "1 month") +
  ggtitle("Sales Trend in Units") +
  theme(
    axis.text.x = element_text(
      size =  8,
      angle = 90,
      vjust = 0.5,
      hjust = 1
    ),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.background = element_rect(colour = "#d4dddd"),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5)
  )

```


# Hierarchies

```{r}

ab_hl<- online_store %>%
  group_by(product_code) %>%
  summarise(Revenue = sum(Revenue),
            Orders = n()) %>%
  ungroup() %>%
  arrange(desc(Revenue)) %>%
  mutate(proportions_rev = Revenue/sum(Revenue), cumulative_rev = cumsum(proportions_rev), 
         ab = case_when( 
           cumulative_rev <= 0.8 ~ "A",
           TRUE ~"B")) %>%
  arrange(desc(Orders)) %>%
  mutate(proportions_ord = Orders/sum(Orders), cumulative_ord = cumsum(proportions_ord), 
         hl = case_when( 
           cumulative_ord <= 0.8 ~ "H",
           TRUE ~"L")) %>%
  select(-Revenue, -Orders, -proportions_rev, -cumulative_rev, -proportions_ord, -cumulative_ord)
  

```


```{r}
table(ab_hl$ab, ab_hl$hl)

```


```{r graph}
online_store %>%
  left_join(ab_hl, by = "product_code") %>%
  mutate(ab_hl = paste0(ab,hl)) %>%
  group_by(ab_hl, InvoiceDate) %>%
  summarise(Quantity = sum(Quantity)) %>%
  ungroup() %>%
  ggplot(aes(InvoiceDate, Quantity, colour = ab_hl)) +
  geom_line() +
  facet_grid(ab_hl~., scales = "free_y")+
   labs(y = "Units Sold") +
  scale_x_date(date_labels = "%b %y", date_breaks  = "1 month") +
  ggtitle("Units Sold Online by Product Group") +
  theme(
    axis.text.x = element_text(
      size =  8,
      angle = 90,
      vjust = 0.5,
      hjust = 1
    ),
    axis.title.x = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.background = element_rect(colour = "#d4dddd"),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5)
  )

```


```{r final dataset}

online_store <- online_store %>%
  left_join(ab_hl, by = "product_code") %>%
  mutate(ab_hl = paste0(ab,hl)) %>%
  filter(ab_hl == "AH") %>%
  group_by(ab_hl, InvoiceDate) %>%
  summarise(Quantity = sum(Quantity)) %>%
  ungroup()

online_store %>% glimpse()

```



# Time Series Analysis


```{r convert to tsibble}

online_store_tsbl<- online_store %>%
  as_tsibble(key = ab_hl, index = InvoiceDate) %>%
  filter_index("2011") %>%
  group_by_key() %>%
  summarise(Quantity = sum(Quantity)) %>%
  ungroup()

online_store_tsbl %>% glimpse()
  
```

```{r}
online_store_tsbl %>%
  autoplot() +
  geom_smooth(method = "lm", se = FALSE)
```


# Missing Values

```{r}

online_store_tsbl %>%
has_gaps(.full = TRUE)

```


```{r}

online_store_tsbl %>%
count_gaps(.full = TRUE) %>% 
  ggplot(aes(.n)) +
  scale_x_log10()+
  geom_histogram(bins = 20)
```

```{r}
online_store_gaps<-
online_store_tsbl %>%
  group_by_key() %>%
  fill_gaps() %>%
  tidyr::fill(Quantity, .direction = "down") %>%
  ungroup()

online_store_gaps %>% has_gaps(.full = TRUE)

```



# Outliers

```{r fig.height=8, fig.width=10}

decomposition<- online_store_gaps %>%
  model(
    stl = STL(Quantity ~ season(period =1), robust = TRUE)
  ) %>%
  components()

 decomposition %>% autoplot()

```

```{r}

outliers <-
  decomposition %>%
  filter(
    remainder < quantile(remainder, 0.25) - 3* IQR(remainder) |
    remainder > quantile(remainder, 0.75) + 3* IQR(remainder)
  )

outliers
```



```{r}
online_store_outliers <-
  online_store_gaps %>%
  anti_join(outliers) %>%
  fill_gaps()
```


```{r}
online_store_clean <-
  online_store_outliers %>%
  model(ARIMA(Quantity)) %>%
  interpolate(online_store_outliers)
```



# Time Series Analysis

```{r}
online_store_clean %>%
  autoplot() +
  geom_smooth(method = "lm", se = FALSE)

```

```{r}

online_store_clean %>% features(Quantity, feat_stl)
```


```{r fig.height=8, fig.width=8}

lagged_sales <-
  online_store_clean %>%
  filter(month(InvoiceDate) > 1)

lagged_sales %>%
  gg_lag(Quantity, geom = "point")+
  labs(x = "lag(Quantity, k)")



```

```{r}

online_store_clean %>%
  ACF(Quantity, lag_max = 28) %>%
  autoplot()


```

```{r}

online_store_clean %>%
  ACF(Quantity, lag_max = 84) %>%
  autoplot()

```


```{r fig.height=8, fig.width=10}
# Decomposition ----
online_store_clean %>%
  model(
    stl = STL(Quantity ~ trend(window = 7) + season(window = "periodic"))
  ) %>%
  components() %>% autoplot()
  
```

# Forecasting

## Train and Test sets


```{r}

online_store_fit <- online_store_clean %>%
  filter(InvoiceDate <= (max(InvoiceDate)-28))

online_store_validate <- online_store_clean %>%
  filter(InvoiceDate > (max(InvoiceDate)-28))

online_store_train <- online_store_fit %>%
  filter(InvoiceDate <= (max(InvoiceDate)-28))

online_store_test <- online_store_fit %>%
  filter(InvoiceDate > (max(InvoiceDate)-28))

```


## Forecasting Methods

```{r}

#Naive ----
fit_naive<- online_store_train %>%
  model(snaive = SNAIVE(Quantity ~ lag("week")))

fc_naive<- fit_naive %>%
  forecast(h = 28) 

fit_naive %>% refit(online_store_test) %>%
  accuracy() %>% 
  select(ab_hl, .model, MAPE, ACF1)

fc_naive %>%
  autoplot(online_store_train %>% filter(InvoiceDate >= "2011-07-01"))

```

```{r}
# Linear Model ----

fit_lm <- online_store_train %>%
  model(
    lm = TSLM(Quantity ~ trend() + season())
  )

fc_lm <- fit_lm %>%
  forecast(h = 28)

fit_lm %>% refit(online_store_test) %>%
  accuracy() %>% 
  select(ab_hl, .model, MAPE, ACF1)

fc_lm %>% autoplot(online_store_train %>% filter(InvoiceDate >= "2011-07-01"))


```

```{r}
# Exponential Smoothing ----

## Simple Exponential Smoothing ----

fit_ses <- online_store_train %>%
  model(
    ets = ETS(Quantity ~ error("A") + trend("N") + season("N"))
  )

fc_ses <- fit_ses %>%
  forecast(h = 28)

fit_ses %>% refit(online_store_test) %>%
  accuracy() %>% 
  select(ab_hl, .model, MAPE, ACF1)

fc_ses %>% autoplot(online_store_train %>% filter(InvoiceDate >= "2011-07-01"))


```


```{r}
# Exponential Smoothing ----

## Holt's Exponential Smoothing ----

fit_hes <- online_store_train %>%
  model(
    ets = ETS(Quantity ~ error("A") + trend("A") + season("N"))
  )

fc_hes <- fit_hes %>%
  forecast(h = 28)

fit_hes %>% refit(online_store_test) %>%
  accuracy() %>% 
  select(ab_hl, .model, MAPE, ACF1)

fc_hes %>% autoplot(online_store_train %>% filter(InvoiceDate >= "2011-07-01"))


```


```{r}
# Exponential Smoothing ----

## Holt - Winter's Exponential Smoothing ----

fit_hwes <- online_store_train %>%
  model(
    ets_additive = ETS(Quantity ~ error("A") + trend("A") + season("A")),
    ets_multiplicative = ETS(Quantity ~ error("M") + trend("A") + season("M")),
    ets_damped = ETS(Quantity ~ error("M") + trend("Ad") + season("M"))
  )

fc_hwes <- fit_hwes %>%
  forecast(h = 28)

fit_hwes %>% refit(online_store_test) %>%
  accuracy() %>% 
  select(ab_hl, .model, MAPE, ACF1)

fc_hwes %>% autoplot(online_store_train %>% filter(InvoiceDate >= "2011-07-01"), level = NULL)


```


```{r}

# Exponential Smoothing ----

## Auto Exponential Smoothing ----

fit_aes <- online_store_train %>%
  model(
    ets = ETS(Quantity)
  )

fit_aes %>% refit(online_store_test) %>%
  accuracy()

report(fit_aes)

```


#Validation

```{r}
## Fit Model ----
fit <- online_store_fit %>%
  model(
    snaive = SNAIVE(Quantity ~ lag("week")),
    lm = TSLM(Quantity ~ trend() + season()),
    ets_additive = ETS(Quantity ~ error("A") + trend("A") + season("A")),
    ets_multiplicative = ETS(Quantity ~ error("M") + trend("A") + season("M")),
    ets_damped = ETS(Quantity ~ error("M") + trend("Ad") + season("M")),
    ets_auto = ETS(Quantity)
  ) 


fit %>%
  refit(online_store_validate) %>%
  accuracy()


fit %>% forecast(h = 28) %>% accuracy(online_store_clean)

```


```{r}
## Fit Model ----

fit <- online_store_clean %>%
  filter(InvoiceDate <= (max(InvoiceDate)-28)) %>%
  model(
    eas = ETS(Quantity)
  ) 

fc<- fit %>%
  forecast(h = 28)

fc %>% accuracy(online_store_clean)

fc %>% autoplot(online_store_clean %>% filter(InvoiceDate >= "2011-07-01"))

```


# Bootstrapping & Forecast Bagging


```{r fig.height=8, fig.width=10}

online_store_stl<- online_store_fit %>%
  model(stl = STL(Quantity))

sim<- online_store_stl %>%
generate(new_data = online_store_fit, times = 100, bootstrap_block_size = 28, seed = 2022) %>%
  select(-.model, -Quantity)

online_store_stl %>%
  generate(new_data = online_store_fit, times = 100, bootstrap_block_size = 28, seed = 2022) %>%
  autoplot(.sim) +
  autolayer(online_store_fit, Quantity) +
  guides(colour = "none") +
  labs(title = "AH Product sales: Bootstrapped series",
       y="Units Sold")
  


```


```{r fig.height=6, fig.width=10}

ets_forecasts <- sim %>%
  model(ets = ETS(.sim)) %>%
  forecast(h= 28)


ets_forecasts %>%
  update_tsibble(key = .rep) %>%
  autoplot(.mean) +
 autolayer(online_store_fit, Quantity) +
  guides(colour = "none") +
  labs(title = "AH Product sales: Bootstrapped series",
       y="Units Sold")

```


```{r fig.height=6, fig.width=10}

bagged <- ets_forecasts %>%
  summarise(bagged_mean = mean(.mean))

bagged_forecasts<- bagged %>%
  mutate(dist = dist_degenerate(bagged_mean)) %>%
  as_fable(response = "Quantity", distribution = dist)

bagged_forecasts %>% accuracy(online_store_clean) %>% mutate(method = "Bagged ETS")

```



```{r}
online_store_fit %>%
  model(ets_auto = ETS(Quantity)) %>%
  forecast(h = 28) %>%
  autoplot(online_store_clean %>% filter(InvoiceDate >= "2011-08-01")) +
  autolayer(bagged, bagged_mean, col = "#D55E00") +
  labs(title = "AH Product sales: Bootstrapped Forecast",
       y="Units Sold")
```









